a_lims: null
n_plans: 2000
horizon: 20
multistep: 1
n_samples_o: 300
n_steps_o: 100
lr_o: 0.0001
lr_o_scaling: null
use_info_gain: false
use_observation_preference: true
use_pragmatic_value: true
scale_pragmatic_value: 1
pragmatic_discounting: -1
pragmatic_type: "normal"
dist_norm: "kl"
n_samples_pr: 200
select_max_pi: true
n_samples_ig_s: 3
n_samples_ig_o: 3
n_samples_obs_pref_s: 100
n_samples_obs_pref_o: 10
n_samples_a: 30
n_samples_a_noise_sys: 100
n_samples_a_combine: 200
use_complete_ukf: true
update_noise_sys_interval: 10
n_samples_noise_sys: 200
n_steps_noise_sys: 100
lr_o_noise_sys: 0.001
update_noise_sys_complete: true
n_samples_combine_belief: 100
use_info_gain_noise_sys: false
exp_normal_sys_params: false
C_index: null
sys_dependent_C: null
state_dependent_C : null
use_beta_VI: false
use_state_based_action_prior: false
state_action_matrix: null
action_prior: null
use_fixed_plans: false
belief_sys_params_box: null
update_action_selection: false
update_action_selection_lr: 0.9
standardise_state: false
state_scaling: null
reaction_time: 0.0